import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>
					Welcome to <a href="https://nextjs.org">Next.js!</a>
				</h1>
				<button className="w-24 m-4 p-4 rounded-sm bg-red-500 text-center text-white">
					テスト
				</button>

				<p className={styles.description}>
					Get started by editing{" "}
					<code className={styles.code}>pages/index.js</code>
				</p>
				<div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 p-4 gap-4">
					<div className="bg-white shadow p-3 rounded lg:w-64">
						<div>
							<div
								style={{ backgroundImage: `url('')` }}
								className="bg-cover bg-center bg-gray-300 h-32 rounded"
							></div>
						</div>
						<div className="mt-6">
							<p className="text-lg text-bold tracking-wide text-gray-600 mb-2">
								趣味
							</p>
							<p className="text-sm text-gray-600 font-hairline">
								ここに趣味のことについて書きたいね。
							</p>
						</div>
					</div>
					<div className="bg-white shadow p-3 rounded lg:w-64">
						<div>
							<div
								style={{ backgroundImage: `url('')` }}
								className="bg-cover bg-center bg-gray-300 h-32 rounded"
							></div>
						</div>
						<div className="mt-6">
							<p className="text-lg text-bold tracking-wide text-gray-600 mb-2">
								好きな食べ物
							</p>
							<p className="text-sm text-gray-600 font-hairline">
								ここに食べ物のことについて書きたいね。
							</p>
						</div>
					</div>
					<div className="bg-white shadow p-3 rounded lg:w-64">
						<div>
							<div
								style={{ backgroundImage: `url('')` }}
								className="bg-cover bg-center bg-gray-300 h-32 rounded"
							></div>
						</div>
						<div className="mt-6">
							<p className="text-lg text-bold tracking-wide text-gray-600 mb-2">
								性格
							</p>
							<p className="text-sm text-gray-600 font-hairline">
								ここに性格のことについて書きたいね。
							</p>
						</div>
					</div>
				</div>
			</main>

			<footer className={styles.footer}>
				<a
					href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
					target="_blank"
					rel="noopener noreferrer"
				>
					Powered by{" "}
					<span className={styles.logo}>
						<Image
							src="/vercel.svg"
							alt="Vercel Logo"
							width={72}
							height={16}
						/>
					</span>
				</a>
			</footer>
		</div>
	);
}
